### PR TITLE
Update group charter for 2024

### PR DESCRIPTION
**Pull request by RupertBenWiser**
Adding decision process to make it clear to the group how decisions are decided.

Add compatibility report as a group deliverable.

### CODE REVIEW

**Review by NiklasMerz — APPROVED** [review]
I vote +1

**Comment by aluhrs13** [comment]
IMO we should resolve https://github.com/WebView-CG/Compatibility-Data-Project/issues/3 and make this charter more explicitly scoped based on that. Right now it's ambiguous if we're targeting the web-facing API surface or the native-side API surface.

**Comment by RupertBenWiser** [comment]
> IMO we should resolve [WebView-CG/Compatibility-Data-Project#3](https://github.com/WebView-CG/Compatibility-Data-Project/issues/3) and make this charter more explicitly scoped based on that. Right now it's ambiguous if we're targeting the web-facing API surface or the native-side API surface.

Thanks for the call out! To reposition that a little, do we consider the ambiguity a bug or a feature? Lets discuss that in the group today before we land this change. I can update this in real time based on the outcome.

**Comment by RupertBenWiser** [comment]
We have decided to keep the scope open to the behaviours of WebViews as a whole. We have updated the charter to not focus on "APIs". I have an AI on me from the meeting to re-focus some of the compatibility project issues with this lens.

**Pull request merged**
